### ISSUE TITLE
@clerk/clerk-sdk-node ClerkAPIResponseError: Unprocessable Entity - getUserOauthAccessToken google

### ISSUE THREAD

**Issue by AlonMiz** [clerk/javascript#1827]
### Description

**Steps to reproduce:**

1. Authorize user with Google and a `gmail.send,gmail.readonly` scopes
2. refresh the browser or wait a few hours
3. use server-side `clerk.users.getUserOauthAccessToken(userId, 'oauth_google');` 
4. getting `ClerkAPIResponseError: Unprocessable Entity` error

* When using the method right after the authentication with Google, everything works fine

**Expected behavior:**

I would expect the code not to throw and be able to get the OAuth token, even when the last token is expired, using the refresh token it fetched in the initial authentication

**Actual behavior:**

The getUserOauthAccessToken mechanism seems not to handle situation when it needs to refresh the OAuth token

![image](https://github.com/clerkinc/javascript/assets/1812912/3b87114b-7ec2-4c19-9144-ce419972cc0c)

### Publishable key

pk_test_cHJvcGVyLXNwYXJyb3ctNDkuY2xlcmsuYWNjb3VudHMuZGV2JA

### Environment

```Shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 70.92 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
    pnpm: 8.5.0 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 106.1.44.105
    Chrome: 117.0.5938.132
    Safari: 16.6
  npmPackages:
    @clerk/clerk-sdk-node: ^4.12.6 => 4.12.6 
    @clerk/nextjs: ^4.24.0 => 4.24.0 
    @clerk/themes: ^1.7.6 => 1.7.6 
```

### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerkinc/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction / Replay Link

its pretty hard - if there's no other choice ill try to create one

**Comment by statico** [comment]
I'm still trying to find a reproduction here, but we noticed Clerk auth acting strangely in our React Native / Expo app starting a week ago, and we haven't updated our app in over two weeks. It might be this. I'll report back.

**Comment by clerk-cookie** [comment]
Hello 👋

We currently close issues after 40 days of inactivity. It's been 30 days since the last update here. If we missed this issue, please reply here. Otherwise, we'll close this issue in 10 days.

As a friendly reminder: The best way to see an issue fixed is to open a pull request. If you're not sure how to do that, please check out our [contributing guide](https://github.com/clerk/javascript/blob/main/docs/CONTRIBUTING.md).

Thanks for being a part of the Clerk community! 🙏

**Comment by clerk-cookie** [comment]
Hello again 👋

After 40 days of no activity, we'll close this issue. Keep in mind, I'm just a robot, so if I've closed this issue in error, please reply here and my human colleagues will reopen it.

As a friendly reminder: The best way to see an issue fixed is to open a pull request. If you're not sure how to do that, please check out our [contributing guide](https://github.com/clerk/javascript/blob/main/docs/CONTRIBUTING.md).

Thanks for being a part of the Clerk community! 🙏

**Comment by AlonMiz** [comment]
@thecrayon
actually eventually, it stopped happening... might be a version or something (I moved to clerk core v2

**Comment by jnimmo** [comment]
I've just started running into this issue too. For further context, I'm calling the function inside a cached server action. 
I did some optimisations yesterday where I removed a bunch of unnecessary `const user = await currentUser()` statements, and I wonder whether that could be impacting it. I've added them back in just to see if it reduces the frequency of the problem. 

```
export const getReports = cache(async (propertyId: string, reportId: string): Promise<ReportData> => {
const { userId } = auth();
  if (!userId) {
    throw new Error(`Authentication error`);
  }
  const clerkToken = await clerkClient().users.getUserOauthAccessToken(userId, provider);
})
```

**Comment by muratg98** [comment]
hey has anyone got an update on this issue? the refresh token is not automatically refreshing the access token (im using google oauth). The code again works if I log out and log in again (probably because the access token resets), however why is the refresh token not automatically refreshing the access token as outlined in the documentation? Is it to do with the fact that im in dev mode still and can it fix in production? for reference: ```_ClerkAPIResponseError: Unprocessable Entity errors: [
    {
      code: 'oauth_missing_refresh_token',
      message: 'Cannot refresh OAuth access token',
      longMessage: "The current access token has expired and we cannot refresh it, because the authorization server hasn't provided us with a refresh token",
      meta: [Object]
    }
  ]```

**Comment by jnimmo** [comment]
Can we reopen this issue please?
@muratg98 can you advise what Clerk hooks you’re calling prior to requesting the OAuth token?
In my case I was using auth().protect() which I note is experimental and wondered whether that could have any impact.

**Comment by thecrayon** [comment]
@muratg98 I actually swapped out Clerk for Next Auth- I never got this to work in Clerk. Using Next Auth, I find managing the access/refresh tokens to be much easier (you can clearly see error messages and you have much more control over the user authentication in general).

**Comment by goldsolace** [comment]
@muratg98 I'm also running into this issue. Using Google OAuth like the other's who have experienced this. The token isn't getting refreshed and after an hour calling `getUserOauthAccessToken` causes throws the following error.

`errors: [
    {
      code: 'oauth_missing_refresh_token',
      message: 'Cannot refresh OAuth access token',
      longMessage: "The current access token has expired and we cannot refresh it, because the authorization server hasn't provided us with a refresh token",
      meta: [Object]
    }
  ]`

Happens both in Dev and Prod environments.

**Comment by jnimmo** [comment]
> @muratg98 I'm also running into this issue. Using Google OAuth like the other's who have experienced this. The token isn't getting refreshed and after an hour calling `getUserOauthAccessToken` causes throws the following error.
> 
> `errors: [ { code: 'oauth_missing_refresh_token', message: 'Cannot refresh OAuth access token', longMessage: "The current access token has expired and we cannot refresh it, because the authorization server hasn't provided us with a refresh token", meta: [Object] } ]`
> 
> Happens both in Dev and Prod environments.

The problem is due to the same OAuth application being used for Clerk Dev and Prod environments; the refresh token is only provided to whichever Clerk environment authenticates an account first. 
The solution is to ensure you use two separate projects in Google Cloud, one for Clerk Dev and one for Clerk Prod.

**Comment by sergesteban** [comment]
> > @muratg98 I'm also running into this issue. Using Google OAuth like the other's who have experienced this. The token isn't getting refreshed and after an hour calling `getUserOauthAccessToken` causes throws the following error.
> > `errors: [ { code: 'oauth_missing_refresh_token', message: 'Cannot refresh OAuth access token', longMessage: "The current access token has expired and we cannot refresh it, because the authorization server hasn't provided us with a refresh token", meta: [Object] } ]`
> > Happens both in Dev and Prod environments.
> 
> The problem is due to the same OAuth application being used for Clerk Dev and Prod environments; the refresh token is only provided to whichever Clerk environment authenticates an account first. The solution is to ensure you use two separate projects in Google Cloud, one for Clerk Dev and one for Clerk Prod.

oh wow, i just got into the same issue 
thanks for the hint @jnimmo

**Comment by jescalan** [comment]
This is correct - also we are tracking this specific issue and looking to get a fix implemented internally so this wouldn't be the case anymore, in case that is helpful

**Comment by sergesteban** [comment]
just for the record, it happens when using python lib, and clerk api
`
    print(f'user_id: {user_id}')
    print(f'provider: {provider}')
    print(f'clerk_api_key: {clerk_api_key}')
    url = f"https://api.clerk.com/v1/users/{user_id}/oauth_access_tokens/{provider}"
    headers = {"Authorization": f"Bearer {clerk_api_key}"}
    response = requests.get(url, headers=headers)
    print(f'Response: {response.json()}')
`

response:
`
Response: {'errors': [{'message': 'Cannot refresh OAuth access token', 'long_message': "The current access token has expired and we cannot refresh it, because the authorization server hasn't provided us with a refresh token", 'code': 'oauth_missing_refresh_token'}], 'clerk_trace_id': '1b224db015e456bf624e4e2d1b3f2860'}
`

**Comment by LauraBeatris** [comment]
Hey everyone, I'm a Software Engineer from @clerk SDK team 👋 

The `refresh_token` is only provided by Google during the initial user authorization. Subsequent authorizations, like those made while testing an OAuth2 integration, will not return the `refresh_token` again, and therefore calls to `getUserOauthAccessToken` end up failing.

Clerk will handle these cases, so you won't need to manage Identity Provider-specific behaviors. We will soon implement an API change that redirects users to Google for consent again if a refresh token is missing, requiring no action on your part.

**Comment by AlonMiz** [comment]
> Hey everyone, I'm a Software Engineer from @clerk SDK team 👋
> 
> The `refresh_token` is only provided by Google during the initial user authorization. Subsequent authorizations, like those made while testing an OAuth2 integration, will not return the `refresh_token` again, and therefore calls to `getUserOauthAccessToken` end up failing.
> 
> Clerk will handle these cases, so you won't need to manage Identity Provider-specific behaviors. We will soon implement an API change that redirects users to Google for consent again if a refresh token is missing, requiring no action on your part.

The issue is more significant than initially described. The core problem lies in the reuse of the same refresh_token for both user login and scope upgrades.

### Scenario:

- Initial Authorization: When a user first connects their Google account, a refresh_token is obtained with the default scopes.
- Adding Additional Scopes: If the user decides to connect additional services, such as Gmail or Calendar, through an in-app button, a new refresh_token is generated that includes the extended scopes (e.g., Gmail).
- Subsequent Logins: On subsequent sign-ins, the system uses the original refresh_token, which lacks the extended scopes. As a result, the additional permissions (e.g., Gmail access) are no longer available.


### Implications:

- Inconsistent Behavior: The refresh token used during login is downgraded, causing the loss of previously granted additional scopes.
- Security Concerns: Requesting non-essential scopes during every sign-in can pose security risks from the user's perspective.
- Incremental Authorization: This issue contradicts the principle of incremental authorization, where additional permissions should be requested only when necessary, without affecting the initial authentication flow.

### Desired Outcome:

- Separate Tokens for Different Purposes: Ensure that the refresh_token used for login remains unchanged and only requests mandatory scopes.
- Scoped Token Upgrades: When users opt to add new scopes, generate a separate refresh_token that includes these additional permissions without impacting the existing login token.
- By addressing this, we can maintain consistent authentication behavior and enhance security by adhering to the principles of incremental authorization.

**Comment by rogueturnip** [comment]
I'm curious to find out about this ticket, last update was Jan 5th.  I see it's not planned but is there some sort of work around when you have something that's used for login AND for accessing Google APIs?

**Comment by jescalan** [comment]
@rogueturnip this functionality should be working as expected, we have many using it for this purpose without issue. if it's not working in your case, please [reach out to our support team](https://clerk.com/contact/support) and we'll try to get you some help!

**Comment by samuelcastro** [comment]
I'm using a custom oauth token for different tools in the app (gmail, calendar, notion), each one has their one custom oauth auth, so I created on clerk `oauth_custom_gmail`, after users connect their account their are able to use just fine, however after some minutes I get `Unable to retrieve OAuth token: Unprocessable Entity`. Using `@clerk/backend`.

@jescalan Any updates on this? Isn't there a refresh token mechanisms in the backend for custom oauth?

**Comment by AlonMiz** [comment]
Just FYI
I eventually implemented this manually...
😔

**Comment by grantsingleton** [comment]
This is still an issue im not sure why no one at clerk has been able to reproduce. For anyone at clerk reading this: you have to have requested scopes beyond the basic google scopes that clerk needs, wait an hour, and then try to call getUserOauthAccessToken and you will get an UnprocessableEntity error. Should be really easy to repro. @jescalan 

EDIT: I may have figured out why this happens. If you sign up with a google account on dev, and then use that same google account in prod, google doesn't issue another refresh token. Same for deleting a user. My suspicion is that google only issues a refresh token the first time that google account is authed for that app and if you ever break that via deleting the user on clerk and re-signing up or by having signed up on dev AND prod, you will run into this issue.
